apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: INVENTORY_URL
              value: "http://inventory:8001"
          ports:
            - containerPort: 8000
            - containerPort: 9465
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 9465
      targetPort: 9465
  type: ClusterIP
  