version: "3.9"

services:
  inventory:
    build: ./services/inventory
    container_name: inventory
    ports:
      - "8001:8001"
      - "9464:9464"

  order:
    build: ./services/order
    container_name: order
    environment:
      - INVENTORY_URL=http://inventory:8001
    depends_on:
      - inventory
    ports:
      - "8000:8000"
      - "9465:9465"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - inventory
      - order

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus